kind: pipeline
type: docker
name: default

workspace:
  path: /root

steps:
  - name: install
    image: ubuntu:latest
    pull: if-not-exists
    commands:
      - echo ". $HOME/trash.sh" > $HOME/.bashrc
      - . $HOME/.bashrc
      - ls -la $HOME/.trash/
      - type trash

  - name: test trash_empty
    depends_on:
      - install
    image: ubuntu:latest
    pull: if-not-exists
    commands:
      - /bin/bash
      - . $HOME/.bashrc
      - for i in 1 2 3 4; do touch /tmp/testfile$i; done
      - ls -l /tmp
      - trash /tmp/testfile*
      - ls -l /tmp
      - trash_list
      - ls -la $HOME/.trash/
      - trash_empty
      - ls -la $HOME/.trash/

  - name: test trash_restore
    depends_on:
      - install
    image: ubuntu:latest
    pull: if-not-exists
    commands:
      - /bin/bash
      - . $HOME/.bashrc
      - for i in 1 2 3 4; do touch /tmp/testfile$i; done
      - ls -l /tmp
      - trash /tmp/testfile*
      - ls -l /tmp
      - trash_list
      - ls -la $HOME/.trash/
      - trash_restore
      - ls -l /tmp
      - ls -la $HOME/.trash/

  - name: test trash_rm
    depends_on:
      - install
    image: ubuntu:latest
    pull: if-not-exists
    commands:
      - /bin/bash
      - . $HOME/.bashrc
      - for i in 1 2 3 4; do touch /tmp/testfile$i; done
      - ls -l /tmp
      - trash /tmp/testfile*
      - ls -l /tmp
      - trash_list
      - ls -la $HOME/.trash/
      - trash_rm testfile2 testfile3
      - trash_list
      - ls -la $HOME/.trash/